version: "3"

services:

  nitter:
    # image: zedeus/nitter:latest
    build: ./
    networks:
      - captain-overlay-network
    container_name: nitter
    ports:
      - "8081:8081" # Replace with "8080:8080" if you don't use a reverse proxy
    volumes:
      - ./nitter.conf:/src/nitter.conf:ro
    depends_on:
      - nitter-redis
    restart: unless-stopped

  nitter-redis:
    image: redis:6-alpine
    container_name: nitter-redis
    command: redis-server --save 60 1 --loglevel warning
    volumes:
      - nitter-redis:/data
    restart: unless-stopped
    networks:
      - captain-overlay-network

volumes:
  nitter-redis:

networks:
  captain-overlay-network:
    external: true
